export const STORAGE_KEY = "schemaforge-workspace-v1";

export type Column = {
  id: string;
  name: string;
  type: string;
  primaryKey: boolean;
  nullable: boolean;
};

export type SchemaTable = {
  id: string;
  name: string;
  position: { x: number; y: number };
  columns: Column[];
};

export type Relation = {
  id: string;
  source: string;
  sourceColumnId: string;
  target: string;
  targetColumnId: string;
};

export type Workspace = {
  name: string;
  tables: SchemaTable[];
  relations: Relation[];
};

const column = (id: string, name: string, type: string, primaryKey = false, nullable = false): Column => ({
  id,
  name,
  type,
  primaryKey,
  nullable,
});

export function ecommerceSample(): Workspace {
  return {
    name: "E-commerce Database",
    tables: [
      {
        id: "users",
        name: "users",
        position: { x: 80, y: 90 },
        columns: [
          column("users-id", "id", "uuid", true),
          column("users-name", "full_name", "varchar(120)"),
          column("users-email", "email", "varchar(255)"),
          column("users-created", "created_at", "timestamptz"),
        ],
      },
      {
        id: "products",
        name: "products",
        position: { x: 690, y: 85 },
        columns: [
          column("products-id", "id", "uuid", true),
          column("products-name", "name", "varchar(160)"),
          column("products-sku", "sku", "varchar(64)"),
          column("products-price", "price", "numeric(10,2)"),
        ],
      },
      {
        id: "orders",
        name: "orders",
        position: { x: 330, y: 395 },
        columns: [
          column("orders-id", "id", "uuid", true),
          column("orders-user", "user_id", "uuid"),
          column("orders-status", "status", "varchar(32)"),
          column("orders-total", "total", "numeric(10,2)"),
          column("orders-created", "created_at", "timestamptz"),
        ],
      },
      {
        id: "order_items",
        name: "order_items",
        position: { x: 900, y: 420 },
        columns: [
          column("items-id", "id", "uuid", true),
          column("items-order", "order_id", "uuid"),
          column("items-product", "product_id", "uuid"),
          column("items-quantity", "quantity", "integer"),
          column("items-price", "unit_price", "numeric(10,2)"),
        ],
      },
    ],
    relations: [
      { id: "orders-user", source: "orders", sourceColumnId: "orders-user", target: "users", targetColumnId: "users-id" },
      { id: "items-order", source: "order_items", sourceColumnId: "items-order", target: "orders", targetColumnId: "orders-id" },
      { id: "items-product", source: "order_items", sourceColumnId: "items-product", target: "products", targetColumnId: "products-id" },
    ],
  };
}

export function freshWorkspace(): Workspace {
  return {
    name: "Untitled schema",
    tables: [
      {
        id: "table-1",
        name: "users",
        position: { x: 200, y: 170 },
        columns: [
          column("column-1", "id", "uuid", true),
          column("column-2", "email", "varchar(255)"),
        ],
      },
    ],
    relations: [],
  };
}

const quote = (identifier: string) => `"${identifier.replaceAll('"', '""')}"`;

export function postgresSql(workspace: Workspace): string {
  const blocks = workspace.tables.map((table) => {
    const lines = table.columns.map((field) => {
      const notNull = field.primaryKey || !field.nullable ? " NOT NULL" : "";
      return `  ${quote(field.name || "unnamed_column")} ${field.type || "text"}${notNull}`;
    });

    const primaryKeys = table.columns.filter((field) => field.primaryKey);
    if (primaryKeys.length) {
      lines.push(`  PRIMARY KEY (${primaryKeys.map((field) => quote(field.name || "unnamed_column")).join(", ")})`);
    }

    workspace.relations
      .filter((relation) => relation.source === table.id)
      .forEach((relation) => {
        const sourceColumn = table.columns.find((field) => field.id === relation.sourceColumnId);
        const targetTable = workspace.tables.find((item) => item.id === relation.target);
        const targetColumn = targetTable?.columns.find((field) => field.id === relation.targetColumnId);
        if (sourceColumn && targetTable && targetColumn) {
          lines.push(
            `  FOREIGN KEY (${quote(sourceColumn.name || "unnamed_column")}) REFERENCES ${quote(targetTable.name || "unnamed_table")} (${quote(targetColumn.name || "unnamed_column")})`,
          );
        }
      });

    return `CREATE TABLE ${quote(table.name || "unnamed_table")} (\n${lines.join(",\n")}\n);`;
  });

  return `-- Generated by SchemaForge\n-- PostgreSQL schema: ${workspace.name}\n\n${blocks.join("\n\n")}`;
}

export function validateWorkspace(workspace: Workspace): string[] {
  const messages: string[] = [];
  const seenTables = new Set<string>();
  workspace.tables.forEach((table) => {
    const normalized = table.name.trim().toLowerCase();
    if (!normalized) messages.push("Every table needs a name.");
    if (seenTables.has(normalized)) messages.push(`Table name “${table.name}” is duplicated.`);
    seenTables.add(normalized);

    const seenColumns = new Set<string>();
    table.columns.forEach((field) => {
      const columnName = field.name.trim().toLowerCase();
      if (!columnName) messages.push(`${table.name || "A table"} has an unnamed column.`);
      if (seenColumns.has(columnName)) messages.push(`Column “${field.name}” is duplicated in ${table.name}.`);
      seenColumns.add(columnName);
    });
    if (!table.columns.length) messages.push(`${table.name || "A table"} has no columns.`);
  });

  workspace.relations.forEach((relation) => {
    const targetTable = workspace.tables.find((table) => table.id === relation.target);
    const targetColumn = targetTable?.columns.find((field) => field.id === relation.targetColumnId);
    if (!targetColumn) messages.push("A relationship points to a deleted column.");
    else if (!targetColumn.primaryKey) messages.push(`${targetTable?.name}.${targetColumn.name} should be a primary key before it is referenced.`);
  });
  return [...new Set(messages)];
}
